### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by steveperskine** [jbesw/aws-serverless-form-handler#4]
Hi James 
I've been having some issue getting this handler working, specifically with the CORS policy.  When submitting the form its erroring out. Console reports:  Access to XMLHttpRequest at 'https://guqjdlil59.execute-api.eu-west-2.amazonaws.com/Prod' from origin 'http://edgyunderwear.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

When I run Enable CORS on the post method of the API its failing on the last one  Add Access-Control-Allow-Origin Integration Response Header Mapping to POST method .

When running a test in the API Console. The request sent to Lambada receives a 200 response but the Endpoint response body before transformations is receiving a 500 response, 

For the front end I've used you Gist Serverless Form Example, changing the api end point to my own.

I've spent the entire day try to fix this but I have had to admit defeat in the hope you can help.

Thanks  STEVE

**Comment by jbesw** [comment]
Hi Steve! I'd recommend using Postman to see which headers are being sent back with the API call - I find this is the easiest way to make sure everything is working as expected. 

The 500 error from the console test is caused by the payload not being present, so the Lambda function is throwing that error - that's all normal. 

If you can double-check the headers and you are not seeing anything, can you paste your Lambda handler here (and template.yaml if you have changed it) and I can look further.

**Comment by hector6921** [comment]
Hi James,
I ran into that problem as well, my solution  configure your Method integration request to lambda and adding the ARN of your function and then deploy again. Hope this helps.

**Comment by jbesw** [comment]
Hi Hector - thanks for sharing! Steve, let me know if you are still having any issues with this.
